apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guestbook
resources:
- guestbook-ns.yaml
- guestbook-deploy.yaml
- guestbook-svc.yaml
images:
- name: public.ecr.aws/nginx/nginx
  newTag: 1.27.1
